import Head from 'next/head'
import Navbar from '@/components/util/Navbar'
import About from '@/components/About/About'

export default function Index() {
    return (
        <>
            <Head>
                <title>About | Tom O'Donoavn</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <About />
        </>
    )
}
